version: '3.8'

services:
  frontend:
    build:
      context: ./game
      dockerfile: Dockerfile
    ports:
      - "3000:5000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # env_file:
    #   - .env

